spring:
  application:
    name: raizesnordeste
  datasource:
    url: jdbc:postgresql://localhost:5432/raizes_db
    username: raizes_user
    password: raizes_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true