spring:
  application:
    name: raizesnordeste
  datasource:
    url: jdbc:postgresql://localhost:5432/raizes_db
    username: raizes_user
    password: raizes_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:UmFpemVzTm9yZGVzdGVTdXBlclNlY3JldEtleVBhcmFBc3NpbmF0dXJhSldUMjAyNg==}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}